import React from "react";
import { CloudSun, UserCheck, Calculator, Sparkles } from "lucide-react";
import { useTranslation } from "../../i18n/LanguageContext";

export type ProvenanceType =
  | "LIVE WEATHER"
  | "USER-PROVIDED DATA"
  | "ESTIMATED RECOMMENDATION"
  | "DEMO AI ASSESSMENT";

interface ProvenanceBadgeProps {
  type?: ProvenanceType;
  source?: ProvenanceType;
  className?: string;
  size?: "sm" | "md";
}

export const ProvenanceBadge: React.FC<ProvenanceBadgeProps> = ({
  type,
  source,
  className = "",
  size = "sm",
}) => {
  const { t } = useTranslation();
  const effectiveType = type || source || "USER-PROVIDED DATA";

  const getBadgeConfig = () => {
    switch (effectiveType) {
      case "LIVE WEATHER":
        return {
          bg: "bg-sky-50 text-sky-700 border-sky-200",
          icon: <CloudSun className={size === "sm" ? "w-3 h-3" : "w-3.5 h-3.5"} />,
          label: t("provenance.liveWeather", "LIVE WEATHER"),
          tooltip: t("provenance.liveWeatherDesc", "Fetched in real-time from Open-Meteo satellite & meteorological models"),
        };
      case "USER-PROVIDED DATA":
        return {
          bg: "bg-emerald-50 text-emerald-700 border-emerald-200",
          icon: <UserCheck className={size === "sm" ? "w-3 h-3" : "w-3.5 h-3.5"} />,
          label: t("provenance.userProvided", "USER-PROVIDED DATA"),
          tooltip: t("provenance.userProvidedDesc", "Field parameters entered and verified by the farm operator"),
        };
      case "ESTIMATED RECOMMENDATION":
        return {
          bg: "bg-amber-50 text-amber-800 border-amber-200",
          icon: <Calculator className={size === "sm" ? "w-3 h-3" : "w-3.5 h-3.5"} />,
          label: t("provenance.estimatedRecommendation", "ESTIMATED RECOMMENDATION"),
          tooltip: t("provenance.estimatedRecommendationDesc", "Calculated via FAO-56 Penman-Monteith & agronomic microclimate threshold models"),
        };
      case "DEMO AI ASSESSMENT":
        return {
          bg: "bg-indigo-50 text-indigo-700 border-indigo-200",
          icon: <Sparkles className={size === "sm" ? "w-3 h-3" : "w-3.5 h-3.5"} />,
          label: t("provenance.demoAiAssessment", "DEMO AI ASSESSMENT"),
          tooltip: t("provenance.demoAiAssessmentDesc", "Generated by computer vision & Gemini model for educational evaluation"),
        };
      default:
        return {
          bg: "bg-slate-100 text-slate-700 border-slate-200",
          icon: null,
          label: effectiveType,
          tooltip: "",
        };
    }
  };

  const config = getBadgeConfig();
  const sizeClasses = size === "sm" ? "text-[10px] px-2 py-0.5 gap-1" : "text-xs px-2.5 py-1 gap-1.5";

  return (
    <span
      title={config.tooltip}
      className={`inline-flex items-center font-bold tracking-wider uppercase rounded-full border shadow-2xs ${config.bg} ${sizeClasses} ${className}`}
    >
      {config.icon}
      <span>{config.label}</span>
    </span>
  );
};

